---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/work
    #machine:
    #  image: circleci/classic:latest
    docker:
      - image: ubuntu:bionic

    steps:
      - checkout
#      - restore_cache:
#          key: tbw-build-dependencies-v1-{{ .Branch }}

      - run: pwd; ls -al; id -a
      - run: apt update &&
          apt install -y
          zip grep file ca-certificates autotools-dev autoconf
          git bc wget rsync cmake make pkg-config yasm libtool
          libasound2-dev

      - run: mkdir -p build_dir ; cd build_dir ; bash -x ../circle_scripts/deps.sh
      - run: cd build_dir ; bash -x ../circle_scripts/tbw.sh '../'

#      - save_cache:
#          paths: [ "~/work/cache" ]
#          key: tbw-build-dependencies-v1-{{ .Branch }}

#      - store_artifacts:
#          path: ~/work/pi-gen/deploy2
#          destination: deploy


