---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/work
    #machine:
    #  image: circleci/classic:latest
    docker:
      - image: ubuntu:bionic

    steps:
      - checkout
#      - restore_cache:
#          key: tbw-build-dependencies-v1-{{ .Branch }}

      - run: pwd; ls -al; id -a
      - run: apt update &&
          apt install -y --no-install-recommends
            zip grep rsync xz-utils file git curl
            git bc wget rsync

      # add ToxBlinkenwall custom build stuff ----------

#      - save_cache:
#          paths: [ "~/work/cache" ]
#          key: tbw-build-dependencies-v1-{{ .Branch }}

#      - store_artifacts:
#          path: ~/work/pi-gen/deploy2
#          destination: deploy


