---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - build

jobs:
  build:
    working_directory: ~/work
    #machine:
    #  image: circleci/classic:latest
    docker:
      - image: ubuntu:bionic

    steps:
      - run: pwd; ls -al; id -a
      - run: apt update &&
          apt install -y
          zip grep file ca-certificates autotools-dev autoconf automake
          git bc wget rsync cmake make pkg-config yasm libtool
          libasound2-dev libv4l-dev ssh gzip tar
          python3-pip

      - checkout
      - restore_cache:
          key: tbw-build-dependencies-v3-{{ .Branch }}

      - run: python3 --version
      - run: ls -al; pwd

      # test python scripts
      - run: python3 -m pip install evdev
      - run: mkdir -p _test_python_/
      - run:
          name: test-python-script
          command: cd _test_python_/;pwd;ls -al;ls -al ../toxblinkenwall/ext_keys_scripts/ext_keys_evdev.py;python3 ../toxblinkenwall/ext_keys_scripts/ext_keys_evdev.py
          background: true
      - run: cd _test_python_/;ps auxww;sleep 3; ps auxww;ls -al ../ext_keys.fifo

      - run: mkdir -p ~/work/deploy
      - run: if [ -e build_dir ]; then export oo="cache" ; else export oo="" ; fi ; mkdir -p build_dir ; cd build_dir ; bash ../circle_scripts/deps.sh "$oo"
      - run: cd build_dir ; bash ../circle_scripts/tbw.sh '../'

      - save_cache:
          paths: [ "~/work/build_dir" ]
          key: tbw-build-dependencies-v3-{{ .Branch }}

      - store_artifacts:
          path: ~/work/deploy
          destination: deploy


